export const SQL_SERVER_RESERVED_WORDS = [
    'CREATE', 'TABLE', 'PRIMARY', 'KEY', 'FOREIGN', 'REFERENCES',
    'NOT', 'NULL', 'INT', 'VARCHAR', 'BOOLEAN', 'DATE', 'UUID',
    'AUTO_INCREMENT', 'DEFAULT', 'UNIQUE', 'CHECK', 'CONSTRAINT'
  ];
  
  